// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace PhamVanNhan441.Migrations
{
    [DbContext(typeof(PhamVanNhan441DbContext))]
    partial class PhamVanNhan441DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PhamVanNhan441.Models.CompanyPVN441", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyPVN441");
                });

            modelBuilder.Entity("PhamVanNhan441.Models.PVN0441", b =>
                {
                    b.Property<string>("PVNID")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PVNGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PVNName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PVNID");

                    b.ToTable("PVN0441");
                });
#pragma warning restore 612, 618
        }
    }
}
